"""wallet feature

Revision ID: 7679193c14ed
Revises: f7ed8ff0137a
Create Date: 2026-09-21 14:59:28.010012

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '7679193c14ed'
down_revision: Union[str, None] = 'f7ed8ff0137a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


payment_method_enum = sa.Enum('WALLET', 'RAZORPAY', name='payment_method')


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    payment_method_enum.create(op.get_bind(), checkfirst=True)

    op.create_table('wallet_transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('booking_id', sa.UUID(), nullable=True),
    sa.Column('type', sa.Enum('TOPUP', 'BOOKING_PAYMENT', 'BOOKING_REFUND', name='wallet_transaction_type'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('balance_after', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.Enum('CREATED', 'SUCCESS', 'FAILED', 'REFUNDED', name='wallet_txn_status'), nullable=False),
    sa.Column('razorpay_order_id', sa.String(length=255), nullable=True),
    sa.Column('razorpay_payment_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('bookings', sa.Column('payment_method', payment_method_enum, nullable=False, server_default='RAZORPAY'))
    op.add_column('users', sa.Column('wallet_balance', sa.Numeric(precision=10, scale=2), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'wallet_balance')
    op.drop_column('bookings', 'payment_method')
    op.drop_table('wallet_transactions')
    # ### end Alembic commands ###
    payment_method_enum.drop(op.get_bind(), checkfirst=True)
